[package]
name = "image-rs-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
leptess = "0.14.0"
screenshots = "0.5.1"
